

##Prepare Environment

In [1]:
!pip install --upgrade pip
!pip install --upgrade datasets[audio] transformers accelerate evaluate jiwer tensorboard gradio

Requirement already satisfied: pip in /usr/local/lib/python3.12/dist-packages (24.1.2)
Collecting pip
  Downloading pip-26.1-py3-none-any.whl.metadata (4.6 kB)
Downloading pip-26.1-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 38.5 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 24.1.2
    Uninstalling pip-24.1.2:
      Successfully uninstalled pip-24.1.2
Successfully installed pip-26.1
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Collecting transformers
  Downloading transformers-5.7.0-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Collecting jiwer
  Downloading jiwer-4.0.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: tensorboard in /usr/local/lib/python3.12/dist-packages (2.20.0)
Requirement already satisfied: gradio in /usr/local/lib/python3.12/dist-packages (5.50.0)
Collecting gradio
  Downloading gradio-6.14.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: datasets[audio] in /usr/local/lib/python3.12/dist-packages (4.0.0)
Collecting datasets[audio]
  Downloading datasets-4.8.5-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets[audio]) (3.29.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets[audio]) (2.0.2)
Collecting pyarrow>=21.0.0 (from datasets[audio])
  Downloading pyarrow-24.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets[audio]) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets[audio]) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets[audio]) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets[audio]) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets[audio]) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets[audio]) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets[audio]) (0.70.16)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets[audio]) (2025.3.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from datasets[audio]) (1.11.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets[audio]) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets[audio]) (6.0.3)
Requirement already satisfied: torchcodec>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from datasets[audio]) (0.10.0+cu128)
Requirement already satisfied: torch>=2.8.0 in /usr/local/lib/python3.12/dist-packages (from datasets[audio]) (2.10.0+cu128)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets[audio]) (3.13.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets[audio]) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets[audio]) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets[audio]) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets[audio]) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets[audio]) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets[audio]) (1.4.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets[audio]) (0.24.2)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets[audio]) (4.15.0)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: click>=8.1.8 in /usr/local/lib/python3.12/dist-packages (from jiwer) (8.3.3)
Collecting rapidfuzz>=3.9.7 (from jiwer)
  Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Requirement already satisfied: absl-py>=0.4 in /usr/local/lib/python3.12/dist-packages (from tensorboard) (1.4.0)
Requirement already satisfied: grpcio>=1.48.2 in /usr/local/lib/python3.12/dist-packages (from tensorboard) (1.80.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard) (3.10.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from tensorboard) (11.3.0)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in /usr/local/lib/python3.12/dist-packages (from tensorboard) (5.29.6)
Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard) (75.2.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard) (3.1.8)
Requirement already satisfied: brotli>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.2.0)
Requirement already satisfied: fastapi<1.0,>=0.115.2 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.136.1)
Collecting gradio-client==2.5.0 (from gradio)
  Downloading gradio_client-2.5.0-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: groovy~=0.1 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.1.2)
Collecting hf-gradio<1.0,>=0.4.1 (from gradio)
  Downloading hf_gradio-0.4.1-py3-none-any.whl.metadata (428 bytes)
Requirement already satisfied: jinja2<4.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.0.3)
Requirement already satisfied: orjson~=3.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.11.8)
Requirement already satisfied: pydantic<=3.0,>=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.12.3)
Requirement already satisfied: pydub<1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.25.1)
Requirement already satisfied: python-multipart<1.0,>=0.0.18 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.0.26)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.12/dist-packages (from gradio) (2025.2)
Requirement already satisfied: safehttpx<0.2.0,>=0.1.7 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.1.7)
Requirement already satisfied: semantic-version~=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.10.0)
Requirement already satisfied: starlette<2.0,>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.52.1)
Requirement already satisfied: tomlkit<0.15.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.13.3)
Requirement already satisfied: uvicorn>=0.14.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.46.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1.0,>=0.115.2->gradio) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1.0,>=0.115.2->gradio) (0.0.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets[audio]) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets[audio]) (2026.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<=3.0,>=2.0->gradio) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<=3.0,>=2.0->gradio) (2.41.4)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets[audio]) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets[audio]) (13.9.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets[audio]) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets[audio]) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets[audio]) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets[audio]) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets[audio]) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets[audio]) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets[audio]) (1.23.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets[audio]) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets[audio]) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets[audio]) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets[audio]) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets[audio]) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets[audio]) (0.1.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->datasets[audio]) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->datasets[audio]) (3.6.1)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->datasets[audio]) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->datasets[audio]) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->datasets[audio]) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->datasets[audio]) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->datasets[audio]) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->datasets[audio]) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->datasets[audio]) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->datasets[audio]) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->datasets[audio]) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->datasets[audio]) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->datasets[audio]) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->datasets[audio]) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->datasets[audio]) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->datasets[audio]) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->datasets[audio]) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->datasets[audio]) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.8.0->datasets[audio]) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.8.0->datasets[audio]) (1.5.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.8.0->datasets[audio]) (1.3.0)
Downloading datasets-4.8.5-py3-none-any.whl (528 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 529.0/529.0 kB 7.5 MB/s  0:00:00
Downloading transformers-5.7.0-py3-none-any.whl (10.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.5/10.5 MB 20.8 MB/s  0:00:00
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
Downloading jiwer-4.0.0-py3-none-any.whl (23 kB)
Downloading gradio-6.14.0-py3-none-any.whl (19.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.7/19.7 MB 29.5 MB/s  0:00:00
Downloading gradio_client-2.5.0-py3-none-any.whl (59 kB)
Downloading hf_gradio-0.4.1-py3-none-any.whl (4.5 kB)
Downloading pyarrow-24.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (48.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 MB 24.6 MB/s  0:00:01
Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 37.1 MB/s  0:00:00
Installing collected packages: rapidfuzz, pyarrow, jiwer, gradio-client, datasets, transformers, hf-gradio, evaluate, gradio
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 18.1.0
    Uninstalling pyarrow-18.1.0:
      Successfully uninstalled pyarrow-18.1.0
  Attempting uninstall: gradio-client
    Found existing installation: gradio_client 1.14.0
    Uninstalling gradio_client-1.14.0:
      Successfully uninstalled gradio_client-1.14.0
  Attempting uninstall: datasets
    Found existing installation: datasets 4.0.0
    Uninstalling datasets-4.0.0:
      Successfully uninstalled datasets-4.0.0
  Attempting uninstall: transformers
    Found existing installation: transformers 5.0.0
    Uninstalling transformers-5.0.0:
      Successfully uninstalled transformers-5.0.0
  Attempting uninstall: gradio
    Found existing installation: gradio 5.50.0
    Uninstalling gradio-5.50.0:
      Successfully uninstalled gradio-5.50.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9/9 [gradio]
Successfully installed datasets-4.8.5 evaluate-0.4.6 gradio-6.14.0 gradio-client-2.5.0 hf-gradio-0.4.1 jiwer-4.0.0 pyarrow-24.0.0 rapidfuzz-3.14.5 transformers-5.7.0

In [2]:
!pip install -U transformers datasets

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.7.0)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.8.5)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.11.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (24.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)

## Login to HF

In [3]:
from huggingface_hub import notebook_login

notebook_login()

## Load Dataset

In [4]:
!apt-get install -y jq

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
jq is already the newest version (1.6-2.1ubuntu3.1).
0 upgraded, 0 newly installed, 0 to remove and 42 not upgraded.

In [5]:
!RESPONSE=$(curl -X POST "https://mozilladatacollective.com/api/datasets/cmn2cxzy701iumm077t5ayw0e/download" \
  -H "Authorization: Bearer API-KEY" \
  -H "Content-Type: application/json") && \
DOWNLOAD_URL=$(echo $RESPONSE | jq -r '.downloadUrl') && \
curl -L -o "hindi_cv.tar.gz" "$DOWNLOAD_URL"

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   890    0   890    0     0   1084      0 --:--:-- --:--:-- --:--:--  1084
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  544M  100  544M    0     0  60.7M      0  0:00:08  0:00:08 --:--:-- 72.1M

## Extract dataset

In [6]:
!tar -xvzf hindi_cv.tar.gz

Streaming output truncated to the last 5000 lines.
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579833.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579835.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579836.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579838.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579839.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579843.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579844.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579845.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579846.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579847.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579853.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579854.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579855.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579856.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579857.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579863.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579864.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579865.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579866.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579867.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579873.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579874.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579875.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579876.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579877.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579880.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579881.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579882.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579883.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579884.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579893.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579895.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579896.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579898.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579899.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579901.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579902.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579903.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579904.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579905.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579911.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579912.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579913.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579914.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579915.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579921.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579922.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579923.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579924.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579925.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579929.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579930.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579931.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579932.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579933.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579934.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579935.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579936.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579937.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37579938.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37630551.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37630552.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37630553.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37630554.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37630555.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37630557.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37630559.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37630561.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37630563.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37630565.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37630566.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37630567.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37630568.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37630570.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37630572.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37630579.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37630581.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37630583.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37630584.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37630585.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37630591.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37630593.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37630595.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37630596.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37630598.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37695869.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37695870.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37695871.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37695872.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37695873.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37754359.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37754360.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37754361.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37754362.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37754363.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37803367.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37803368.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37803369.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37803370.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37803371.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37817520.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37817521.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37817522.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37817523.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37817524.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37868075.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37868076.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37868077.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37868078.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37868079.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37873511.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37873512.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37873513.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37873514.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37873515.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37890679.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37890680.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37890681.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37890682.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37890683.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_37895003.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38091216.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38091217.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38091218.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38091219.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38091220.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108115.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108116.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108117.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108118.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108119.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108132.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108134.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108136.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108138.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108139.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108148.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108150.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108152.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108156.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108159.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108160.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108161.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108162.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108163.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108165.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108175.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108176.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108177.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108178.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108179.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108188.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108190.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108192.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108193.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108194.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108202.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108205.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108207.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108208.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108209.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108212.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108215.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108217.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108218.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108219.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108230.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108231.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108232.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108233.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108234.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108240.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108241.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108242.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108243.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108244.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108255.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108256.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108257.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108258.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38108259.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38110551.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38110552.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38110553.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38110554.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38110555.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38110566.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38110567.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38110568.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38110569.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38110571.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38110586.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38110587.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38110588.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38110589.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38110590.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38110601.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38110602.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38110603.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38110604.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38110605.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38110618.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38110620.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38110622.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38110624.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38110625.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112096.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112097.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112098.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112099.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112100.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112106.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112109.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112112.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112114.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112115.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112121.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112122.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112123.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112124.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112125.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112131.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112132.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112133.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112134.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112135.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112141.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112142.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112143.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112144.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112145.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112155.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112156.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112157.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112158.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112159.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112165.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112166.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112167.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112168.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112169.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112170.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112171.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112172.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112173.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112175.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112185.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112186.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112187.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112188.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112189.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112195.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112196.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112197.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112198.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112199.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112200.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112201.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112202.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112203.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112204.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112210.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112211.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112212.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112213.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112214.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112220.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112221.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112222.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112223.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112224.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112225.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112226.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112227.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112228.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112229.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112235.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112236.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112237.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112238.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112239.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112245.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112246.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112247.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112248.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112250.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112255.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112256.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112257.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112258.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112259.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112265.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112266.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112267.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112268.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112269.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112270.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112272.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112275.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112278.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112279.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112280.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112281.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112282.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112283.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112284.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112285.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112286.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112287.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112288.mp3
cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_38112289.mp3

## Load it into Python

In [7]:
import pandas as pd
import os

data_dir = "/content/cv-corpus-25.0-2026-03-09/hi"

train_df = pd.read_csv(f"{data_dir}/train.tsv", sep="\t")
test_df = pd.read_csv(f"{data_dir}/test.tsv", sep="\t")

# Prepend the full path to the audio files
train_df["path"] = data_dir + "/clips/" + train_df["path"]
test_df["path"] = data_dir + "/clips/" + test_df["path"]

train_df.head()

,client_id,path,sentence_id,sentence,sentence_domain,up_votes,down_votes,age,gender,accents,variant,locale,segment
0,0f018a99663f33afbb7d38aee281fb1afcfd07f9e7acd0...,/content/cv-corpus-25.0-2026-03-09/hi/clips/co...,6cd05fc0979a495e7008b614e213c3cac9926dae51ac76...,हमने उसका जन्मदिन मनाया।,NaN,2,0,NaN,NaN,NaN,NaN,hi,NaN
1,0f018a99663f33afbb7d38aee281fb1afcfd07f9e7acd0...,/content/cv-corpus-25.0-2026-03-09/hi/clips/co...,76bb7b27759e9acf98f9709f962731ad21362a9a8278be...,"साउथ दिल्ली नगर निगम सख्त, शॉपिंग मॉल के बाहर ...",NaN,2,0,NaN,NaN,NaN,NaN,hi,NaN
2,0f018a99663f33afbb7d38aee281fb1afcfd07f9e7acd0...,/content/cv-corpus-25.0-2026-03-09/hi/clips/co...,6f74cd7cea0efbcf45411b70e1eab18ffd4f3e344d332c...,उत्तर कोरिया ने अमेरिका को दी हमले की धमकी,NaN,2,0,NaN,NaN,NaN,NaN,hi,NaN
3,0f018a99663f33afbb7d38aee281fb1afcfd07f9e7acd0...,/content/cv-corpus-25.0-2026-03-09/hi/clips/co...,758c421b84cdaf0ff497c9f62f4d51fc270d4f3c89a013...,अगले कमरे में अनेक रोमन मूर्तियाँ हैं।,NaN,2,0,NaN,NaN,NaN,NaN,hi,NaN
4,0f018a99663f33afbb7d38aee281fb1afcfd07f9e7acd0...,/content/cv-corpus-25.0-2026-03-09/hi/clips/co...,8454c34fb7e19a1d5bd7a859ec4cf1e54237e7d326716f...,तुम ने टॉम को कहाँ भेज दिया?,NaN,2,1,NaN,NaN,NaN,NaN,hi,NaN

In [8]:
train_df.sample(800,random_state=42).shape

(800, 13)

In [9]:
# /content/cv-corpus-25.0-2026-03-09/hi/clips/common_voice_hi_23795238.mp3
train_df['path']

0       /content/cv-corpus-25.0-2026-03-09/hi/clips/co...
1       /content/cv-corpus-25.0-2026-03-09/hi/clips/co...
2       /content/cv-corpus-25.0-2026-03-09/hi/clips/co...
3       /content/cv-corpus-25.0-2026-03-09/hi/clips/co...
4       /content/cv-corpus-25.0-2026-03-09/hi/clips/co...
                              ...
4889    /content/cv-corpus-25.0-2026-03-09/hi/clips/co...
4890    /content/cv-corpus-25.0-2026-03-09/hi/clips/co...
4891    /content/cv-corpus-25.0-2026-03-09/hi/clips/co...
4892    /content/cv-corpus-25.0-2026-03-09/hi/clips/co...
4893    /content/cv-corpus-25.0-2026-03-09/hi/clips/co...
Name: path, Length: 4894, dtype: object

## Convert to Hugging Face Dataset

In [10]:
from datasets import Dataset

train_dataset = Dataset.from_pandas(train_df)
test_dataset = Dataset.from_pandas(test_df.sample(1200,random_state=42))

## Add audio column

In [11]:
from datasets import Audio

train_dataset = train_dataset.cast_column(
    "path", Audio(sampling_rate=16000)
)

test_dataset = test_dataset.cast_column(
    "path", Audio(sampling_rate=16000)
)

In [12]:
train_dataset[0]['path']['array']

array([ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
       -1.06715824e-07,  2.32571423e-07,  8.11920415e-08], dtype=float32)

### rename `path` → `audio`

In [13]:
train_dataset = train_dataset.rename_column("path", "audio")
test_dataset = test_dataset.rename_column("path", "audio")

In [14]:
from datasets import load_dataset, DatasetDict

common_voice = DatasetDict()

common_voice["train"] = train_dataset
common_voice["test"] = test_dataset

print(common_voice)

DatasetDict({
    train: Dataset({
        features: ['client_id', 'audio', 'sentence_id', 'sentence', 'sentence_domain', 'up_votes', 'down_votes', 'age', 'gender', 'accents', 'variant', 'locale', 'segment'],
        num_rows: 4894
    })
    test: Dataset({
        features: ['client_id', 'audio', 'sentence_id', 'sentence', 'sentence_domain', 'up_votes', 'down_votes', 'age', 'gender', 'accents', 'variant', 'locale', 'segment', '__index_level_0__'],
        num_rows: 1200
    })
})

In [15]:
common_voice = common_voice.remove_columns(['sentence_domain', 'up_votes', 'down_votes', 'age', 'gender', 'accents', 'variant', 'locale', 'segment','sentence_id','client_id'])

In [16]:
common_voice

DatasetDict({
    train: Dataset({
        features: ['audio', 'sentence'],
        num_rows: 4894
    })
    test: Dataset({
        features: ['audio', 'sentence', '__index_level_0__'],
        num_rows: 1200
    })
})

### Load Whisper processor

In [17]:
from transformers import WhisperFeatureExtractor

feature_extractor = WhisperFeatureExtractor.from_pretrained("openai/whisper-small")

preprocessor_config.json: 0.00B [00:00, ?B/s]

In [18]:
from transformers import WhisperTokenizer

tokenizer = WhisperTokenizer.from_pretrained("openai/whisper-small", language="Hindi", task="transcribe")

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

normalizer.json: 0.00B [00:00, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

In [19]:
def normalize(text):
    return text.strip()

In [20]:
input_str = normalize(common_voice["train"][0]["sentence"])
labels = tokenizer(input_str).input_ids
decoded_with_special = tokenizer.decode(labels, skip_special_tokens=False)
decoded_str = tokenizer.decode(labels, skip_special_tokens=True)

print(f"Input:                 {input_str}")
print(f"Decoded w/ special:    {decoded_with_special}")
print(f"Decoded w/out special: {decoded_str}")
print(f"Are equal:             {input_str == decoded_str}")

[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer WhisperTokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

Input:                 हमने उसका जन्मदिन मनाया।
Decoded w/ special:    <|startoftranscript|><|hi|><|transcribe|><|notimestamps|>हमने उसका जन्मदिन मनाया।<|endoftext|>
Decoded w/out special: हमने उसका जन्मदिन मनाया।
Are equal:             True

In [21]:
from transformers import WhisperProcessor

processor = WhisperProcessor.from_pretrained("openai/whisper-small")

config.json: 0.00B [00:00, ?B/s]

In [22]:
def prepare_dataset(batch):
    audio = batch["audio"]

    batch["input_features"] = processor.feature_extractor(
        audio["array"],
        sampling_rate=audio["sampling_rate"]
    ).input_features[0]

    batch["labels"] = processor.tokenizer(batch["sentence"]).input_ids

    return batch

In [23]:
common_voice = common_voice.map(prepare_dataset, remove_columns=common_voice.column_names["train"])

Map:   0%|          | 0/4894 [00:00<?, ? examples/s]

Map:   0%|          | 0/1200 [00:00<?, ? examples/s]

In [24]:
from transformers import WhisperForConditionalGeneration

model = WhisperForConditionalGeneration.from_pretrained("openai/whisper-small")

model.safetensors:   0%|          | 0.00/967M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/479 [00:00<?, ?it/s]

generation_config.json: 0.00B [00:00, ?B/s]

In [25]:
model.generation_config.language = "hindi"
model.generation_config.task = "transcribe"

model.generation_config.forced_decoder_ids = None
model.config.suppress_tokens = []

In [26]:
from dataclasses import dataclass
from typing import Any, Dict, List, Union
import torch

@dataclass
class DataCollatorSpeechSeq2SeqWithPadding:
    processor: Any  # Usually a Wav2Vec2Processor or WhisperProcessor
    decoder_start_token_id: int

    def __call__(self, features: List[Dict[str, Union[List[int], torch.Tensor]]]) -> Dict[str, torch.Tensor]:
        # Separate audio and label features
        input_features = [{"input_features": f["input_features"]} for f in features]
        label_features = [{"input_ids": f["labels"]} for f in features]

        # Pad audio features
        batch = self.processor.feature_extractor.pad(
            input_features,
            return_tensors="pt"
        )

        # Pad labels
        labels_batch = self.processor.tokenizer.pad(
            label_features,
            return_tensors="pt"
        )

        # Replace padding token id's in labels by -100 so they are ignored by loss
        labels = labels_batch["input_ids"].masked_fill(
            labels_batch["attention_mask"].ne(1), -100
        )

        # Ensure decoder start token is set
        labels[labels[:, 0] != self.decoder_start_token_id, 0] = self.decoder_start_token_id

        batch["labels"] = labels
        return batch

In [27]:
data_collator = DataCollatorSpeechSeq2SeqWithPadding(
    processor=processor,
    decoder_start_token_id=model.config.decoder_start_token_id,
)

In [28]:
import evaluate

metric = evaluate.load("wer")

Downloading builder script: 0.00B [00:00, ?B/s]

In [29]:
def compute_metrics(pred):
    pred_ids = pred.predictions
    label_ids = pred.label_ids

    label_ids[label_ids == -100] = tokenizer.pad_token_id

    pred_str = tokenizer.batch_decode(pred_ids, skip_special_tokens=True)
    label_str = tokenizer.batch_decode(label_ids, skip_special_tokens=True)

    wer = 100 * metric.compute(predictions=pred_str, references=label_str)

    return {"wer": wer}

In [31]:
from transformers import Seq2SeqTrainingArguments

training_args = Seq2SeqTrainingArguments(
    output_dir="./whisper-small-hin",  # change to a repo name of your choice
    per_device_train_batch_size=8,
    gradient_accumulation_steps=2,  # increase by 2x for every 2x decrease in batch size
    learning_rate=1e-3,
    warmup_steps=250,
    # max_steps=5000,
    num_train_epochs=4,
    gradient_checkpointing=True,
    fp16=True,
    eval_strategy="steps",
    per_device_eval_batch_size=8,
    predict_with_generate=True,
    generation_max_length=225,
    save_steps=1000,
    eval_steps=1000,
    logging_steps=25,
    report_to=["tensorboard"],
    load_best_model_at_end=True,
    metric_for_best_model="wer",
    greater_is_better=False,
    push_to_hub=True,
)

In [32]:
from transformers import Seq2SeqTrainer

trainer = Seq2SeqTrainer(
    args=training_args,
    model=model,
    train_dataset=common_voice["train"],
    eval_dataset=common_voice["test"],
    data_collator=data_collator,
    compute_metrics=compute_metrics,
    processing_class=processor,
)

In [ ]:
trainer.train()

[transformers] The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
[transformers] A custom logits processor of type <class 'transformers.generation.logits_process.SuppressTokensLogitsProcessor'> has been passed to `.generate()`, but it was also created in `.generate()`, given its parameterization. The custom <class 'transformers.generation.logits_process.SuppressTokensLogitsProcessor'> will take precedence. Please check the docstring of <class 'transformers.generation.logits_process.SuppressTokensLogitsProcessor'> to see related `.generate()` flags.
[transformers] A custom logits processor of type <class 'transformers.generation.logits_process.SuppressTokensAtBeginLogitsProcessor'> has been passed to `.generate()`, but it was also created in `.generate()`, given its parameterization. The custom <class 'transformers.generation.logits_process.SuppressTokensAtBeginLogitsProcessor'> will take precedence. Please check the docstring of <class 'transformers.generation.logits_process.SuppressTokensAtBeginLogitsProcessor'> to see related `.generate()` flags.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
kwargs = {
    "dataset_tags": "mozilla-foundation/common_voice_25_0",
    "dataset": "common_voice",  # Use a simpler name for the dataset
    "dataset_args": "hi",
    "language": "hi",
    "model_name": "Whisper Small Hi - Lokesh Gaur",  # a 'pretty' name for your model
    "finetuned_from": "openai/whisper-small",
    "tasks": "automatic-speech-recognition",
}

In [ ]:
trainer.push_to_hub(**kwargs)

In [1]:
from transformers import WhisperForConditionalGeneration, WhisperProcessor

model = WhisperForConditionalGeneration.from_pretrained("lkgaur/whisper-small-hin")
processor = WhisperProcessor.from_pretrained("lkgaur/whisper-small-hin")

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/967M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/479 [00:00<?, ?it/s]

generation_config.json: 0.00B [00:00, ?B/s]

processor_config.json:   0%|          | 0.00/409 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [ ]:
from transformers import pipeline
import gradio as gr

# Explicitly set the task for the pipeline
pipe = pipeline("automatic-speech-recognition", model="lkgaur/whisper-small-hin")

def transcribe(audio):
    text = pipe(audio)["text"]
    return text

iface = gr.Interface(
    fn=transcribe,
    inputs=gr.Audio(sources=["microphone"], type="filepath"),
    outputs="text",
    title="Whisper Small Hindi",
    description="Realtime demo for Hindi speech recognition using a fine-tuned Whisper small model.",
)

iface.launch()